version: "3.9"

services:
  admin:
    image: "admin:${TAG}"
    container_name: admin
    ports:
      - 8080:80
    build:
      context: .
    networks:
      - msf

networks:
  msf:
    driver: bridge
