export const VIEW_CONTRACT_LIST = "VIEW_CONTRACT_LIST";
export const VIEW_ALL_CONTRACT_LIST = "VIEW_ALL_CONTRACT_LIST";
export const VIEW_ADMIN = "VIEW_ADMIN";
export const VIEW_REQUEST_LIST = "VIEW_REQUEST_LIST";
export const VIEW_ALL_WITHDRAW_REQUEST = "VIEW_ALL_WITHDRAW_REQUEST";
export const CREATE_WITHDRAW_REQUEST = "CREATE_WITHDRAW_REQUEST";
export const UPDATE_WITHDRAW_REQUEST = "UPDATE_WITHDRAW_REQUEST";
export const CANCEL_WITHDRAW_REQUEST = "CANCEL_WITHDRAW_REQUEST";

export const ADMIN = "ADMIN";
