/* tslint:disable */
/* eslint-disable */
/**
 * SPG API document
 * This is a SPG API document
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: tpp@tpptechnology.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

